name: Release on Linux

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create release
    runs-on: ubuntu-22.04
    container:
      image: gcc:12.2

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.22.x'

      - name: Setup Python
        run: |
          apt-get update -y
          apt-get install python3-pip -y

      - name: Setup Conan
        run: python3 -m pip install conan

      - name: Install missing dependencies
        run: apt-get install libglew-dev -y

      - name: Configure build
        run: cmake --preset gcc_release -B "build"

      - name: Build all
        run: cmake --build "build" -j "$(nproc)"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/bin/*"
          body: Linux binaries
          tag: latest
          allowUpdates: true

